FROM node:18-alpine

WORKDIR /app

ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=""

# ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="dv6keahg3"
# ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}


COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3050
CMD npm run start