FROM node:18-alpine

WORKDIR /app

ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3050
CMD npm run dev