name: Publish Image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_PUBLIC_EMAIL_JS_SERVICEID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_SERVICEID }}
          envkey_NEXT_PUBLIC_EMAIL_JS_TEMPLATEID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_TEMPLATEID }}
          envkey_NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY }}
          envkey_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          envkey_POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}
          envkey_POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
          envkey_POSTGRES_DB_HOST: ${{ secrets.POSTGRES_DB_HOST }}
          envkey_POSTGRES_DB_PORT: ${{ secrets.POSTGRES_DB_PORT }}
          envkey_POSTGRES_DB_DATABASE: ${{ secrets.POSTGRES_DB_DATABASE }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_OAUTH_ID: ${{ secrets.OAUTH_ID }}
          envkey_OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          envkey_AUTH_REDIRECT_PROXY_URL: ${{ secrets.AUTH_REDIRECT_PROXY_URL }}
          envkey_DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: build
        run: |
          docker build . -t joshlehmandev/portfolio-2024:latest
      - name: publish
        run: |
          docker login -u joshlehmandev -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push joshlehmandev/portfolio-2024:latest
