name: Publish Image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: joshlehmandev
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_PUBLIC_EMAIL_JS_SERVICEID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_SERVICEID }}
          envkey_NEXT_PUBLIC_EMAIL_JS_TEMPLATEID: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_TEMPLATEID }}
          envkey_NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY }}
          envkey_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          envkey_POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}
          envkey_POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
          envkey_POSTGRES_DB_HOST: ${{ secrets.POSTGRES_DB_HOST }}
          envkey_POSTGRES_DB_PORT: ${{ secrets.POSTGRES_DB_PORT }}
          envkey_POSTGRES_DB_DATABASE: ${{ secrets.POSTGRES_DB_DATABASE }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_OAUTH_ID: ${{ secrets.OAUTH_ID }}
          envkey_OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          envkey_AUTH_REDIRECT_PROXY_URL: ${{ secrets.AUTH_REDIRECT_PROXY_URL }}
          envkey_DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
          file_name: .env
          fail_on_empty: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            joshlehmandev/portfolio-2024:latest
            joshlehmandev/portfolio-2024:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
