name: Publish Image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: build
        run: |
          docker build . -t joshlehmandev/portfolio-2024:latest
      - name: publish
        run: |
          docker login -u joshlehmandev -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push joshlehmandev/portfolio-2024:latest
